services:
  app:
    build: ./uas-backend
    ports:
      - "3000:3000"
    volumes:
      - ./uas-backend:/app
    environment:
      PGUSER: admin
      PGHOST: db
      PGDATABASE: uasdb
      PGPASSWORD: admin123
      PGPORT: 5432
    depends_on:
      - db
      
  db:
    image: postgres:17
    restart: always
    environment:
      POSTGRES_DB: uasdb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./uas-frontend/db-init:/docker-entrypoint-initdb.d

  frontend:
    image: nginx:alpine
    build:
      context: ./uas-frontend
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    volumes:
      - ./uas-frontend:/usr/share/nginx/html:ro  # Ensure files are present and readable
    depends_on:
      - app

volumes:
  postgres_data:
